server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:https://github.com/asimsharf/spring-config-repo.git}
          default-label: ${CONFIG_REPO_BRANCH:main}
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
